# Generated by Django 3.2.7 on 2021-10-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmbutton', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='caretaker',
            name='address',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='first_name',
            field=models.CharField(default='Ushakova', max_length=150, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretaker',
            name='last_name',
            field=models.CharField(default='Katerina', max_length=150, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretaker',
            name='phone_number',
            field=models.CharField(default='050 444 4444', max_length=20, verbose_name='Номер телефону'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Адреса'),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_year',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Рік народження'),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='ivan', max_length=150, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='ivanov', max_length=150, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='050 555 5555', max_length=20, verbose_name='Номер телефону'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
