# Generated by Django 3.2.7 on 2021-10-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmbutton', '0002_auto_20211008_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Коментар'),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='fathers_name',
            field=models.CharField(default='Fatherts', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Коментар'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fathers_name',
            field=models.CharField(default='Fathers', max_length=150),
            preserve_default=False,
        ),
    ]
